### ISSUE TITLE
Use Composer autoloader for class loading to give more extendability for Magallan

### ISSUE THREAD

**Issue by eps90** [andres-montanez/Magallanes#113]
Hello again!
I've been mastering with Magallanes recently and I think it could be nice feature to use composer autoloader for Magallanes class loading. I know that the existing `Mage\Autoload` class is semi-convetional and takes base_dir dynamically, but there are many pros with going this way:
- optimized autoloader - and less work with supporting the current one
- common autoloading for all namespaces in the project - could be helpful with using utility libraries from project where mage is installed _locally_
- **ability to create external extensions repositories** - that's the thing I miss the most.
### _What's my idea about extensions?_

I use many projects based on Symfony2 and every time I'd need to copy my tasks to `.mage/tasks` directory. If I would create an external repo with tasks and commands, like `Symfony2MageExtensionsBundle` it would be much easier to implement and develop them.
### _How extensions should be implemented and developed?_

That's good question. Currently, Magallanes needs tasks and commands to be implemented in corresponding subdirectories in `.mage/` directory. We could create some DI-like mechanism or some index for tasks with full-named-class responsible for them, to get Magallan know, where to search for them:

```
# .mage/tasks.yml
tasks:
  symfony2/cache-clear: MyCustomBundle\MageTasks\SymfonyCacheClearTask
  doctrine/fixtures-load: MyCustomBundle\MageTasks\DoctrineFixturesLoadTask
commands:
  ...
# etc...
```

Of course each of these classes would implement corresponding Abstract class (which would be possible due to project-scoped autoload mechanism, yay!)
### _Ok, but isn't it more complicated than simple copying the tasks into my project?_

The idea above actually can look a bit complicated. But first advantage is to develop one task in one library, which makes everything easier out-of-the-box.
But let's say that some dependant library has implemented a hundred of tasks and for some reason we **must** to use them all at once, the thing becomes a bit problematic. The solution for this issue would be implementing an **extension class** like many extensionable libraries does. The class would parse its own `configuration.yml` file with tasks list and give the application ability to use it.

```
# Acme\MyCustomBundle\config\extension.yml
extension:
  tasks:
    symfony2/cache-clear: MyCustomBundle\MageTasks\SymfonyCacheClearTask
  commands:
    ...
```

Then loading an extension would be as simple as:

```
# .mage/extensions.yml
extensions:
  - Acme\MyCustomBundle\MyCustomExtension
```
### _Looks nice, what are the disadvantages?_

Recently I've noticed there is built-in composer task. It would be impossible to use it because of upper-level composer autload dependency. So deploy from CI that clones our repo would be look like:

```
git clone https:/github.com/acme/myproject.git
composer install
cd myproject
./bin/mage deploy to:production
```
### _Implementation_

I found this project few weeks ago and I use its basics. I haven't noticed such functionallity so please excuse me if such thing **already exists**. I have the whole idea in my head so I can even take care of implementaion into mage. Please tell me what do you think (especially @andres-montanez) and leave your feedback.
