### ISSUE TITLE
Ability to introduce the hostname variable in the deployment path

### ISSUE THREAD

**Issue by ajgarlag** [andres-montanez/Magallanes#12]
Usually I have to deploy applications to hostnames that are really CNAME records pointing to the same physical server.

To avoid collisions on file paths, I always put the hostname in the deployment path.

It would be great to have the ability to modify the **to:** param in the configuration file including the hostname variable

Something like this:

``` yml
#production
deployment:
  ...
  to: /var/www/vhosts/{hostname}/www
hosts:
  - s01.example.com:22
  - s02.example.com
```

would deploy to: `/var/www/vhosts/s01.example.com/www` in one server and to `/var/www/vhosts/s02.example.com/www` in the other one
