### ISSUE TITLE
ssh private keys.

### ISSUE THREAD

**Issue by gudron** [andres-montanez/Magallanes#127]
Hello guys.
I have a question: 
How can I set the path to the private key, which will run through the ssh connection? I could not find in the documentation.

**!Update**
i find it.

```
deployment:
  strategy: rsync
  user: example.com
  from: ./
  to: /path/to/dir/
  identity-file: /path/to/key/some_key #I needed this option
```
