### ISSUE TITLE
Run global task before local. Is it possible?

### ISSUE THREAD

**Issue by gudron** [andres-montanez/Magallanes#142]
Hello guys. I have a question about the deployment strategy.

I think it's logical if any step in the deployment process - not succeed - the deployment process must be stopped. Even if the task fails the only one of numerous servers in the cluster.

In my case, there are several servers with databases. One master server, two slave. I run the migration and seeding tasks only on the master server. Next, the data is replicated to a slave server using database replication mechanism.

Part of the configuration file:

```
hosts:
  host1.example.com:1234:
    tasks:
      on-deploy:
        - migrations
        - setRbacPermissions
        - addTranslations
  host2.example.com:1234:
  host3.example.com:1234:

tasks:
  pre-deploy:
    - composerInstall
  on-deploy:
    - someTask1
    - someTask2
  post-release:
    - clearAccelerationCache
  post-deploy:
    - someTask3
```

Now tasks someTask1, someTask2 will run on each host only after the tasks from the section "on-deploy" host on a server named "host1.example.com". 

But I need to to execute "someTask1" on each server before the tasks will be executed (migrations, setRbacPermissions, addTranslations) on a server named "host1.example.com". 

Does it make sense to add some parameter, such as "run_first", "run_before"?

Example:

```
tasks:
  pre-deploy:
    - composerInstall
  on-deploy:
    - someTask1: run_first 
# OR
    - someTask1: run_before
    - someTask2
  post-release:
    - clearAccelerationCache
  post-deploy:
    - someTask3
```
