### ISSUE TITLE
Run a task from other user.

### ISSUE THREAD

**Issue by gudron** [andres-montanez/Magallanes#143]
hi everyone.
I have a problem with the launch of different tasks on the same server by different users.
Now I solved this problem as follows:

```
hosts:
  123.123.123.123:1234:
    tasks:
      on-deploy:
        - someTask1
        - someTask2
        - someTask3
        - someTask4
        - someTask5
  ultra.mega.sub.domain.com:1234:
    deployment:
      strategy: disabled
      user: differentUser
      identity-file: /path/to/differentUser/private/key
    tasks:
      on-deploy:
        - differentUserTask
tasks:
  pre-deploy:
    - globalTask1
    - globalTask2
  on-deploy:
    - globalTask3
    - globalTask4
  post-release:
  post-deploy:
```

I need to run "differentUserTask" on server "123.123.123.123". 
I can not set 2 times the same ip option "hosts". So I use a "dirty trick" with the domain name that has an A record for ip - "123.123.123.123". 

And it seems that the problem is solved. But what to do when one task you must perform under a different user on all servers?
