### ISSUE TITLE
Excludes:[] -  only a specific folder

### ISSUE THREAD

**Issue by MM-Psiiirus** [andres-montanez/Magallanes#276]
Hiya,
i got a little Problem. My system is using a "/media" folder to store all media files.
This folder gets symlinked into the current release and is ignored by excludes:[] configuration BUT unfortunately an external lib does use this folder name as well so the subfolder "libs/LIB1/media" will be ignored and not uploaded to the server. 

Is there any solution to fix or workaround it?

Cheers,
Toni

```
#stage
deployment:
  user: root
  strategy: targz
  from: ./
  to: /var/www/webXXX/htdocs/staging
  excludes:
    - config/config.inc.php
    - .idea
    - .DS_STORE
    - media # /media isn't working either
releases:
  enabled: true
  max: 3
  symlink: current
  directory: releases
  owner: weXXX:webXXX
hosts:
  - stage.fmuhu.com
tasks:
  pre-deploy:
  on-deploy:
      - filesystem/link-shared-files:
          linked_files:
            - media
  post-release:
  post-deploy:
```
