### ISSUE TITLE
task only be done on only one host [HOTFIX]

### ISSUE THREAD

**Issue by maojindao55** [andres-montanez/Magallanes#358]
My Magallanes vision is 1.06.

when i deploy, most ting going ok.but the custom task only be done only on one host.
on host x.x.x.x, the task not be done. y.y.y.y was ok.

i try change host postion line,  on host y.y.y.y, the task not be done. x.x.x.x was ok.

it seem like ony the last host have the task.

my config file:

```
#production
deployment:
  user: root
  from: ./
  to: /somedir/
  scm:
  excludes:
        - build.xml
releases:
  enabled: true
  max: 5 
  symlink: current
  directory: releases
hosts:
 - x.x.x.x
 - y.y.y.y
tasks:
  pre-deploy:
  on-deploy:
  post-release:
  post-deploy:
        - generateEnv
```
