### ISSUE TITLE
Allow symlink name parameter

### ISSUE THREAD

**Issue by dn5** [andres-montanez/Magallanes#371]
From what I can see in Mage v3, we lost a way to hardcode a symlink directory thus the deployment creates appropriate `releases` and `current`, breaking all old Docker images:

> When using Releases you have to take into account that Magallanes will create a releases directory in the host_path directory, and a symbolic link current which will point to a release inside releases.
  
In Mage v1, we had a following option:

```
releases:
    enabled: true
    max: 5
    symlink: whatever-the-fuck-symlink-i-want
    directory: releases
```

Any chance to get this back? And is there a reason why it's not enabled by default?
