### ISSUE TITLE
Magephp 3.4 problem with excludes files

### ISSUE THREAD

**Issue by elrokket** [andres-montanez/Magallanes#446]
Hello, i dont know if is a bug or configuration problem, i have this mage config:

```
magephp:
  environments:
    development:
      user: root
      branch: develop
      from: ./
      host_path: /var/www/project-new
      releases: 3
      exclude:
        - ./.ddev/*
        - ./web/sites/default/file-one.php
        - ./web/sites/default/file-two.php
        - ./web/sites/default/hosts/*
        - ./web/sites/default/files/*
      hosts:
        - 200.22.1.2.2:2203
      log_dir: ./deploy_logs
      pre-deploy:
      on-deploy:
      on-release:
      post-release:
      post-deploy:
```

the excludes files or folder is not uploading (This is correct) but in development enviroment excludes folder/files are remove. How i can prevent that this folders  from being deleted? i need mantain this files without changes.

Thanks
