### ISSUE TITLE
Deploy - Symfony 6.2.14 - Error

### ISSUE THREAD

**Issue by daniel14145** [andres-montanez/Magallanes#466]
Hi, I have this error: `Stage "Pre Deploy" did not finished successfully, halting command`. I don't know what I make wrong.

![image](https://github.com/andres-montanez/Magallanes/assets/16451076/7bd023df-9e75-45e0-b9bb-b0528a890d6d)
![image](https://github.com/andres-montanez/Magallanes/assets/16451076/76d24a4e-e7d6-4d63-a5ec-0feb1af0849c)

`Symfony 6.2.14 (env: dev, debug: true)`

```
magephp:
    environments:
        production:
            user: myname
            from: ./
            host_path: /home/www
            releases: 4
            exclude:
                - ./var/cache/*
                - ./var/log/*
                - ./web/app_dev.php
            hosts:
                - nameserver.com
            pre-deploy:
                - git/update
                - composer/install
                - composer/dump-autoload
            on-deploy:
                - symfony/cache-warmup: { env: 'dev' }
                - symfony/assets-install: { env: 'dev' }
            on-release:
            post-release:
            post-deploy:
```
