### ISSUE TITLE
some failed deploys in row break symlink current

### ISSUE THREAD

**Issue by merryech0** [andres-montanez/Magallanes#47]
for example:

``` yml
#production
deployment:
  user: deploy
  from: ./
  to: /var/www/mage-test
  excludes:
releases:
  enabled: true
  max: 2
  symlink: current
  directory: releases
hosts:
  - mage-test-host
tasks:
  pre-deploy:
  on-deploy:
    - fail
  post-release:
  post-deploy:
```

Custom task:

``` php
namespace Task;

use Mage\Task\AbstractTask;

class Fail extends AbstractTask
{
    public function getName()
    {
        return 'Fail!!!';
    }

    public function run()
    {
        $result = $this->runCommandRemote('unavailable_command');

        return $result;
    }
}
```

if remove custom task fail from production.yml deployment is successfull.
after successful deploy two failed deploys break a symlink "current"

``` none
$ ls -alh
lrwxrwxrwx  current -> releases/20140402130809
drwxrwxr-x  releases

$ ls -alh releases/
drwxr-xr-x 20140402130830
drwxr-xr-x 20140402130840
```
