### ISSUE TITLE
Pass custom flags to the deployment task

### ISSUE THREAD

**Issue by katalisha** [andres-montanez/Magallanes#62]
I need to pass a custom flag to the rsync task, have you considered how this could be done?
I was thinking of doing a pull request to allow the following in the config

```
strategy:
    rsync:
      - rsyncFlags: -abc

 strategy
    targz:
      - tarCreateFlags: -abc
      - tarExtractFlags: - abc
      - scpFlags: - abc
```
