### ISSUE TITLE
Yaml nesting

### ISSUE THREAD

**Issue by JoeSimsen** [andres-montanez/Magallanes#90]
Hey, 

I'm trying to pass parameters to a task, however do not want to do this on one line. However this does not work:

``` yaml
pre-deploy:
    - testtask:
      folder: test
```

Anyone have an idea what I am doing wrong?
